name: Schedule

on:
  schedule:
    - cron: '0 2 * * *'  # Run every day at 1 o'clock

jobs:
  build-windows-x86_64-rel:
    runs-on: [ windows, builder ]
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-windows-ninja
        with:
          cmake-args: "-DCMAKE_UNITY_BUILD=ON"
          config: "Release"
          bin-dir: "windows-x86_64"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-x86_64
          path: windows-x86_64/
  build-windows-x86_64-dbg:
    runs-on: [ windows, builder ]
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-windows-ninja
        with:
          cmake-args: "-DCMAKE_UNITY_BUILD=OFF"
          config: "Debug"
  build-windows-x86_64-dev:
    runs-on: [ windows, builder ]
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-windows-ninja
        with:
          cmake-args: "-DCMAKE_UNITY_BUILD=OFF"
          config: "RelWithDebInfo"
  build-windows-x86_64-asan:
    runs-on: [ windows, builder ]
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-windows
        with:
          cmake-args: "-A x64"
          config: "Asan"
          bin-dir: "windows-x86_64-asan"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-x86_64-asan
          path: windows-x86_64-asan/
  build-windows-x86_64-clang-rel:
    runs-on: [ windows, builder ]
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-windows
        with:
          cmake-args: "-A x64 -T ClangCL -DCMAKE_UNITY_BUILD=ON"
          config: "Release"
  build-windows-x86_64-clang-dbg:
    runs-on: [ windows, builder ]
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-windows
        with:
          cmake-args: "-A x64 -T ClangCL"
          config: "Debug"
  build-windows-x86_64-clang-dev:
    runs-on: [ windows, builder ]
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-windows
        with:
          cmake-args: "-A x64 -T ClangCL"
          config: "RelWithDebInfo"
  build-windows-arm64-rel:
    runs-on: [ windows, builder ]
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-windows
        with:
          cmake-args: "-A ARM64 -DCMAKE_UNITY_BUILD=ON -DENABLE_VK_IMPL=OFF -DENABLE_DX_IMPL=ON"
          config: "Release"
          bin-dir: "windows-arm64"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-arm64
          path: windows-arm64/
  build-windows-arm64-dbg:
    runs-on: [ windows, builder ]
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-windows
        with:
          cmake-args: "-A ARM64 -DENABLE_VK_IMPL=OFF -DENABLE_DX_IMPL=ON"
          config: "Debug"
  build-windows-arm64-dev:
    runs-on: [ windows, builder ]
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-windows
        with:
          cmake-args: "-A ARM64 -DENABLE_VK_IMPL=OFF -DENABLE_DX_IMPL=ON"
          config: "RelWithDebInfo"
  build-linux-x86_64-rel:
    runs-on: [ linux, builder ]
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-linux
        with:
          cmake-args: "-DCMAKE_UNITY_BUILD=ON"
          config: "Release"
          bin-dir: "linux-x86_64"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-x86_64
          path: linux-x86_64/
  build-linux-x86_64-dbg:
    runs-on: [ linux, builder ]
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-linux
        with:
          cmake-args: ""
          config: "Debug"
  build-linux-x86_64-dev:
    runs-on: [ linux, builder ]
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-linux
        with:
          cmake-args: ""
          config: "RelWithDebInfo"
  build-linux-x86_64-tsan:
    runs-on: [ linux, builder ]
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-linux
        with:
          cmake-args: "-DCMAKE_UNITY_BUILD=ON"
          config: "Tsan"
          bin-dir: "linux-x86_64-tsan"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-x86_64-tsan
          path: linux-x86_64-tsan/
  build-macos-universal-rel:
    runs-on: [ macos, builder ]
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-macos
        with:
          cmake-args: '-DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -DCMAKE_UNITY_BUILD=ON'
          config: "Release"
          bin-dir: "macos-universal"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macos-universal
          path: macos-universal/
  build-macos-universal-dbg:
    runs-on: [ macos, builder ]
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-macos
        with:
          cmake-args: '-DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"'
          config: "Debug"
  build-macos-universal-dev:
    runs-on: [ macos, builder ]
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-macos
        with:
          cmake-args: '-DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"'
          config: "RelWithDebInfo"
  test-windows-x86_64-cpu:
    runs-on: [ windows, x86_64 ]
    needs:
      - build-windows-x86_64-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-dir: "windows-x86_64"
          test-args: "--nogpu"
  test-windows-x86_64-gpu-nv:
    runs-on: [ windows, x86_64, nv ]
    needs:
      - build-windows-x86_64-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-dir: "windows-x86_64"
          test-args: "--device NV --nocpu"
  test-windows-x86_64-gpu-amd:
    runs-on: [ windows, x86_64, amd ]
    needs:
      - build-windows-x86_64-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-dir: "windows-x86_64"
          test-args: "--device AMD --nocpu"
  test-windows-x86_64-gpu-arc:
    runs-on: [ windows, x86_64, arc ]
    needs:
      - build-windows-x86_64-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-dir: "windows-x86_64"
          test-args: "--device Arc --nocpu"
  test-windows-x86_64-gpu-xe:
    runs-on: [ windows, x86_64, xe ]
    needs:
      - build-windows-x86_64-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-dir: "windows-x86_64"
          test-args: "--device Xe --nocpu"
  test-windows-arm64-cpu:
    runs-on: [ windows, arm64 ]
    needs:
      - build-windows-arm64-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-dir: "windows-arm64"
          test-args: "--nogpu"
  test-windows-arm64-gpu-adreno:
    runs-on: [ windows, arm64, adreno ]
    needs:
      - build-windows-arm64-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-dir: "windows-arm64"
          test-args: "--device Adreno --nocpu"
  test-linux-x86_64-cpu:
    runs-on: [ linux, x86_64 ]
    needs:
      - build-linux-x86_64-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-dir: "linux-x86_64"
          test-args: "--nogpu"
  test-linux-x86_64-gpu-amd:
    runs-on: [ linux, x86_64, amd ]
    needs:
      - build-linux-x86_64-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-dir: "linux-x86_64"
          test-args: "--device AMD --nocpu --nohwrt"
  test-linux-x86_64-gpu-nv:
    runs-on: [ linux, x86_64, nv ]
    needs:
      - build-linux-x86_64-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-dir: "linux-x86_64"
          test-args: "--device NV --nocpu"
  test-macos-arm64-cpu:
    runs-on: [ macos, arm64 ]
    needs:
      - build-macos-universal-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-dir: "macos-universal"
          test-args: "--nogpu"
  test-macos-arm64-gpu-m1:
    runs-on: [ macos, arm64, m1 ]
    needs:
      - build-macos-universal-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-dir: "macos-universal"
          test-args: "--device M1 --nocpu"
  test-macos-x86_64-cpu:
    runs-on: [ macos, x86_64 ]
    needs:
      - build-macos-universal-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-dir: "macos-universal"
          test-args: "--nogpu"
  test-windows-x86_64-cpu-sse2:
    runs-on: [ windows, x86_64, win10 ]
    needs:
      - build-windows-x86_64-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test-sde
        with:
          bin-dir: "windows-x86_64"
          test-args: "--arch SSE2 --nogpu"
          sde-args: "-p4p"
  test-windows-x86_64-cpu-sse41:
    runs-on: [ windows, x86_64, win10 ]
    needs:
      - build-windows-x86_64-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test-sde
        with:
          bin-dir: "windows-x86_64"
          test-args: "--arch SSE41 --nogpu"
          sde-args: "-pnr"
  test-windows-x86_64-cpu-avx:
    runs-on: [ windows, x86_64 ]
    needs:
      - build-windows-x86_64-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test-sde
        with:
          bin-dir: "windows-x86_64"
          test-args: "--arch AVX --nogpu"
          sde-args: "-snb"
  test-windows-x86_64-cpu-avx2:
    runs-on: [ windows, x86_64 ]
    needs:
      - build-windows-x86_64-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test-sde
        with:
          bin-dir: "windows-x86_64"
          test-args: "--arch AVX2 --nogpu"
          sde-args: "-hsw"
  test-windows-x86_64-cpu-avx512:
    runs-on: [ windows, x86_64 ]
    needs:
      - build-windows-x86_64-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test-sde
        with:
          bin-dir: "windows-x86_64"
          test-args: "--arch AVX512 --nogpu"
          sde-args: "-future"
  test-linux-x86_64-cpu-tsan:
    runs-on: [ linux, x86_64 ]
    needs:
      - build-linux-x86_64-tsan
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-name: "test_Ray-tsan"
          bin-dir: "linux-x86_64-tsan"
          test-args: "--nogpu"
  test-windows-x86_64-cpu-asan:
    runs-on: [ windows, x86_64 ]
    needs:
      - build-windows-x86_64-asan
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-name: "test_Ray-asan"
          bin-dir: "windows-x86_64-asan"
          test-args: "--nogpu"
  test-windows-x86_64-gpu-nv-asan:
    runs-on: [ windows, x86_64, nv ]
    needs:
      - build-windows-x86_64-asan
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-name: "test_Ray-asan"
          bin-dir: "windows-x86_64-asan"
          test-args: "--device NV --nocpu"
  test-windows-arm64-cpu-perf:
    runs-on: [ windows, arm64, perf ]
    needs:
      - build-windows-arm64-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-dir: "windows-arm64"
          test-args: "--nogpu --time_limit 2.95"
  test-windows-arm64-gpu-perf:
    runs-on: [ windows, arm64, perf, adreno ]
    needs:
      - build-windows-arm64-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-dir: "windows-arm64"
          test-args: "--nocpu --time_limit 5.4"
