name: 'Test'
inputs:
  bin-dir:
    required: true
  test-args:
    required: true
  sde-args:
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.bin-dir }}
        path: ${{ inputs.bin-dir }}/
    - run: |
        WORK_DIR=`pwd`
        cd ../../builds/Ray/tests
        sde ${{ inputs.sde-args }} -- $WORK_DIR/${{ inputs.bin-dir }}/test_Ray ${{ inputs.test-args }}
      shell: bash
