
image:
    - Visual Studio 2015
    - Visual Studio 2017

clone_folder: c:\projects\Sys

clone_script:
    - git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
    - git checkout -qf %APPVEYOR_REPO_COMMIT%

shallow_clone: true

matrix:
    fast_finish: true

platform:
    - x64
    - x86

configuration:
    - Debug
    - Release
    
init:
    - set arch=
    - if "%PLATFORM%"=="x64" ( set arch= Win64)
    - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
    - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015%arch%" )

before_build:
    - mkdir build_normal
    - mkdir build_unity
    - cd build_normal
    - cmake .. -G %generator% -DENABLE_UNITYBUILD=OFF
    - cd ..\build_unity
    - cmake .. -G %generator% -DENABLE_UNITYBUILD=ON
    - cd ..

build_script:
  - msbuild build_normal\ALL_BUILD.vcxproj
  - msbuild build_unity\ALL_BUILD.vcxproj

test_script:
    - build_normal\tests\%CONFIGURATION%\test_Sys
    - build_unity\tests\%CONFIGURATION%\test_Sys
