language: cpp
compiler: gcc
dist: trusty
env:
- PACKAGE_VERSION="0.0.*"
matrix:
  include:
  - compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-6
    env: COMPILER=g++-6
script:
- mkdir build_normal
- mkdir build_unity
- "(cd build_normal && cmake .. -DENABLE_UNITYBUILD=OFF && make)"
- "(cd build_normal/tests && ./test_Sys)"
- "(cd build_unity && cmake .. -DENABLE_UNITYBUILD=ON && make)"
- "(cd build_unity/tests && ./test_Sys)"


