name: 'Test Img'
inputs:
  bin-dir:
    required: true
  test-args:
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.bin-dir }}
        path: ${{ inputs.bin-dir }}/
    - run: |
        chmod +x ./${{ inputs.bin-dir }}/DemoApp
        WORK_DIR=`pwd`
        cd ../../builds/RayDemo
        cp $WORK_DIR/${{ inputs.bin-dir }}/DemoApp ./
        ./DemoApp ${{ inputs.test-args }} -s assets/scenes/villa.json -w 960 -h 540 $AUX_TEST_ARGS -ref assets/references/villa_cycles.png --output_exr --output_aux --max_samples 256 --psnr 29.17 --threshold 5193 --max_total_depth 16 --transp_depth 48 --iteration_steps 8 --denoise --camera 0
        ./DemoApp ${{ inputs.test-args }} -s assets/scenes/mustang.json -w 960 -h 600 -ref assets/references/mustang_cycles.png --output_exr --output_aux --max_samples 256 --psnr 34.5 --threshold 1939 --refr_depth 12 --max_total_depth 12
        ./DemoApp ${{ inputs.test-args }} -s assets/scenes/bistro.json -w 960 -h 540 -ref assets/references/bistro_cycles.png --output_exr --output_aux --max_samples 256 --psnr 29.75 --threshold 6349
        ./DemoApp ${{ inputs.test-args }} -s assets/scenes/bistro.json -w 960 -h 540 -ref assets/references/bistro_cycles.png --output_exr --output_aux --max_samples 256 --psnr 31.24 --threshold 2980 --use_spatial_cache
        ./DemoApp ${{ inputs.test-args }} -s assets/scenes/bistro_night.json -w 960 -h 540 -ref assets/references/bistro_night_cycles.png --output_exr --output_aux --max_samples 256 --psnr 25.61 --threshold 26245 --camera 0
        ./DemoApp ${{ inputs.test-args }} -s assets/scenes/bistro_night.json -w 960 -h 540 -ref assets/references/bistro_interior_cycles.png --output_exr --output_aux --max_samples 256 --psnr 22.75 --threshold 58830 --camera 1
        ./DemoApp ${{ inputs.test-args }} -s assets/scenes/italian_flat.json -w 900 -h 550 -ref assets/references/italian_flat_cycles.png --output_exr --output_aux --max_samples 256 --diff_depth 8 --spec_depth 8 --refr_depth 12 --max_total_depth 12 --psnr 22.25 --threshold 60506
        ./DemoApp ${{ inputs.test-args }} -s assets/scenes/ai043_01.json -w 700 -h 477 -ref assets/references/ai043_01_cycles.png --output_exr --output_aux --max_samples 256 --diff_depth 2 --spec_depth 2 --psnr 29.57 --threshold 2104
        ./DemoApp ${{ inputs.test-args }} -s assets/scenes/sponza.json -w 960 -h 540 -ref assets/references/sponza_cycles.png --output_exr --output_aux --min_samples 128 --max_samples 256 --variance_threshold 0.00035 --psnr 24.25 --threshold 41928 --diff_depth 2 --max_tex_res 2048
        ./DemoApp ${{ inputs.test-args }} -s assets/scenes/coffee_maker.json -w 640 -h 800 -ref assets/references/coffee_maker_cycles.png --output_exr --output_aux --max_samples 256 --psnr 32.72 --threshold 326 --refr_depth 12 --max_total_depth 12
        ./DemoApp ${{ inputs.test-args }} -s assets/scenes/bathroom.json -w 632 -h 840 -ref assets/references/bathroom_cycles.png --output_exr --output_aux --max_samples 256 --psnr 24.36 --threshold 34152 --refr_depth 12 --max_total_depth 12
        ./DemoApp ${{ inputs.test-args }} -s assets/scenes/staircase.json -w 720 -h 900 -ref assets/references/staircase_cycles.png --output_exr --output_aux --max_samples 256 --psnr 35.21 --threshold 1574 --refr_depth 12 --max_total_depth 12
      shell: bash
